---
title: "ab4"
format: html
editor: visual
---

```{r}
# install.packages("haven")
# install.packages("ggplot2")
# install.packages("car")
# install.packages("plm")
# install.packages("stargazer")
# install.packages("nnet")
# install.packages("MASS")
# install.packages("jtools")
# install.packages("tidyverse")
# install.packages("magrittr")
# install.packages("gridExtra")
# install.packages("lme4")
# install.packages("lmerTest")
# install.packages("interactions")

# Load libraries
library(haven)
library(ggplot2)
library(car)
library(plm)
library(stargazer)
library(nnet)
library(MASS)
library(jtools)
library(tidyverse)
library(magrittr)
library(gridExtra)
library(lme4)
library(lmerTest)
library(interactions)

# Set global options
options(scipen = 100)

```

## Load Data

### AB 4

```{r}
ab4 <- read_sav("ab4.sav")
ab4$year <- 2016 ## all surveys were conducted in 2016
ab4$country<-as.factor(ab4$country) ## Qatar and Yemen doesn't exists
ab4$cname <- ifelse(ab4$country == "1", "Algeria",
                      ifelse(ab4$country == "5", "Egypt",
                        ifelse(ab4$country == "8", "Jordan",
                          ifelse(ab4$country == "10", "Lebanon",
                            ifelse(ab4$country == "13", "Morocco",
                              ifelse(ab4$country == "15", "Palestine",
                                ifelse(ab4$country == "21", "Tunisia", NA)))))))
```

### V-Dem: RoW

```{r}
regimes<-read_csv("political-regime.csv")
regimes$cname<-regimes$Entity
regimes$year<-regimes$Year
regimes$regime<-regimes$"Political regime"
regimes<- regimes[, c("year", "cname", "regime")]
```

### V-Dem Index

```{r}
vdem<-read_csv("V-Dem-CY-Core-v14.csv")
vdem$cname<-vdem$country_name
vdem$cname[vdem$cname == "Palestine/Gaza"] <- "Palestine"       # Replace "Palestine/Gaza" with "Palestine"
vdem_subset <- vdem[, c("year", "cname", "v2x_polyarchy", "v2x_libdem", "v2x_partipdem", "v2x_delibdem", "v2x_egaldem")]
```

### Merge

```{r}
ab4<- merge(ab4, vdem_subset, by = c("cname", "year"), all.x = TRUE)
ab4<- merge(ab4, regimes, by = c("cname", "year"), all.x = TRUE)
```

## Variables

```{r}
### DV- Support for Democracy 
ab4$dem_econ<-ifelse(ab4$q5161>5, NA, as.numeric(ab4$q5161))    
ab4$dem_decisive<-ifelse(ab4$q5162>5, NA, as.numeric(ab4$q5162)) 
ab4$dem_stablity<-ifelse(ab4$q5163>5, NA, as.numeric(ab4$q5163)) 
ab4$dem_better<-ifelse(ab4$q5164>5, NA, 5 - as.numeric(ab4$q5164)) 
ab4$dem_index<-(ab4$dem_decisive+ab4$dem_econ+ab4$dem_stablity)/3           ### Democracy Index 
ab4$deference<-ifelse(ab4$q216>5, NA, 5-as.numeric(ab4$q216)) 
ab4$dem<-Recode(ab4$q516a, "98=NA; 99=NA; 3=2; 1=3; 2=1")                  ### direct support for democracy for multinomial modeling 
ab4$dem_bi<-Recode(ab4$q516a, "98=NA; 99=NA; 3=NA; 2=0")



## PCA for DV Index 

# Subset the data
data_for_pca <- ab4[, c("dem_decisive", "dem_econ", "dem_stablity")]

# Handle missing values by omitting rows with NAs
data_for_pca <- na.omit(data_for_pca)

# Conduct PCA and scale the data
pca_result <- prcomp(data_for_pca, scale. = TRUE)

# Inspect PCA loadings for the first principal component
cat("Loadings for the first principal component:\n")
print(pca_result$rotation[,1])

# Calculate and print the proportion of variance explained by each principal component
explained_variance <- pca_result$sdev^2
total_variance <- sum(explained_variance)
explained_variance_ratio <- explained_variance / total_variance
cat("\nProportion of variance explained by each component:\n")
print(explained_variance_ratio)



## IV - Internet 
ab4$internet_polinfo<-ifelse(ab4$q4101 %in% c(98, 99), NA, 2-ab4$q4101)
ab4$internet_polexpress<-ifelse(ab4$q4102 %in% c(98, 99), NA, 2-ab4$q4102)
ab4$internet_use<-ifelse(ab4$q409 %in% c(98, 99), NA, 7-as.numeric(ab4$q409))  


# Controls
ab4$age <- ifelse(ab4$q1001 %in% c(999), NA, ab4$q1001)
ab4$female<-ifelse(ab4$q1002 ==2, 1, 0)
ab4$educ<-ifelse(ab4$q1003 %in% c(99), NA, as.numeric(ab4$q1003))                                ### education 
ab4$unemployed<-ifelse(ab4$q1004 %in% c(99), NA, as.numeric(ab4$q1004)-1)
ab4$pol_inter<- ifelse(ab4$q404 > 4, NA, 5- as.numeric(ab4$q404))                     ### Political Interest
ab4$gov_trust <- ifelse(ab4$q2011 > 4, NA, 5 - as.numeric(ab4$q2011))                 ### Trust in Gov
ab4$inter_trust<-ifelse(ab4$q103 %in% c(98,99), NA, 2- as.numeric(ab4$q103))          ### interpersonal trust
ab4$single<-ifelse(ab4$q1010 == 1,1,0)
ab4$urban<-ifelse(ab4$q13 ==1, 1, 0)                                                  ### urban
ab4$gov_satis <-ifelse(ab4$q513 > 10, NA, as.numeric(ab4$q513))                       ### Overall gov satis
ab4$religious<-ifelse(ab4$q609 %in% c(98,99), NA, 4- as.numeric(ab4$q609))

ab4$women_work <- ifelse(ab4$q6012 %in% c(98,99), NA, 5-as.numeric(ab4$q6012))
ab4$women_leader <- ifelse(ab4$q6013 %in% c(98,99), NA, as.numeric(ab4$q6013))
ab4$women_educ <- ifelse(ab4$q6014 %in% c(98,99), NA, as.numeric(ab4$q6014))
ab4$women_index <- (ab4$women_work +ab4$women_leader +ab4$women_educ) / 3                   ### Gender Egalitarianism index


                                                          

#interaction variables
ab4$deference_c<-ab4$deference - mean(ab4$deference, trim = 0, na.rm = TRUE)
ab4$info_c<-ab4$internet_polinfo - mean(ab4$internet_polinfo, trim = 0, na.rm = TRUE)
ab4$express_c<-ab4$internet_polexpress - mean(ab4$internet_polexpress, trim = 0, na.rm = TRUE)
ab4$deference_info<-ab4$deference_c*ab4$info_c
ab4$deference_express<-ab4$deference_c*ab4$express_c




## center V-Dem variables 
ab4$elecdem_c<- ab4$v2x_polyarchy - mean(ab4$v2x_polyarchy, na.rm = TRUE, trim = 0)
ab4$libdem_c<- ab4$v2x_libdem - mean(ab4$v2x_libdem, na.rm = TRUE, trim = 0)
ab4$pardem_c<- ab4$v2x_partipdem - mean(ab4$v2x_partipdem, na.rm = TRUE, trim = 0)
ab4$delibdem_c<- ab4$v2x_delibdem - mean(ab4$v2x_delibdem, na.rm = TRUE, trim = 0)
ab4$egaldem_c<- ab4$v2x_egaldem - mean(ab4$v2x_egaldem, na.rm = TRUE, trim = 0)
```

## EDA

```{r}
# plot distribution 
ggplot(ab4, aes(x=dem_index)) + 
  geom_histogram(binwidth=0.5, fill="blue", color="black", alpha=0.7) +
  labs(title="Histogram of Support for Democracy", 
       x="dem_index", 
       y="Frequency") +
  theme_minimal()
```

## Models

```{r}
pdata4 <- pdata.frame(ab4, index = "cname")  ### getting pooled data 

## Main models: polinfo and polexpress 
m1<- plm(dem_index~ internet_polinfo,  data = pdata4, model = "pooling")
m2<- plm(dem_index~ internet_polinfo+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname,  data = pdata4, model = "pooling")
m3<- plm(dem_index~ internet_polexpress,  data = pdata4, model = "pooling")
m4<- plm(dem_index~ internet_polexpress+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname,  data = pdata4, model = "pooling")
m5<- plm(dem_index~ internet_use,  data = pdata4, model = "pooling")
m6<- plm(dem_index~ internet_use+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname,  data = pdata4, model = "pooling")
stargazer(m1, m2, m3, m4, m5, m6, type = "text",
           omit.stat = c("f", "ser"))
```

### Positive Effect of Internet: ab3-4

```{r}
m1<- plm(dem_index~ internet_polinfo,  data = pdata3, model = "pooling")
m2<- plm(dem_index~ internet_polinfo+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname+deference,  data = pdata3, model = "pooling")
m3<- plm(dem_index~ internet_polexpress,  data = pdata3, model = "pooling")
m4<- plm(dem_index~ internet_polexpress+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname+deference,  data = pdata3, model = "pooling")
m5<- plm(dem_index~ internet_polnews,  data = pdata3, model = "pooling")
m6<- plm(dem_index~ internet_polnews+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname+deference,  data = pdata3, model = "pooling")
m7<- plm(dem_index~ internet_polinfo,  data = pdata4, model = "pooling")
m8<- plm(dem_index~ internet_polinfo+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname,  data = pdata4, model = "pooling")
m9<- plm(dem_index~ internet_polexpress,  data = pdata4, model = "pooling")
m10<- plm(dem_index~ internet_polexpress+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname,  data = pdata4, model = "pooling")
stargazer(m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, type = "text", omit.stat = c("f", "ser"))
stargazer(m1, m2, m3, m4, m5, m6, m7, m8,m9, m10, dep.var.labels = c("Support for Democracy"),covariate.labels = c("Internet Pol Info",  "Unemployed", "Interest in Politics", "Age", "Education", "Female(ref:Male)", "Religiosity", "Trust in Gov","Single", "Urban", "Algeria", "Egypt", "Jordan", "Lebanon", "Libya",  "Morocco", "Sudan",  "Deference to Gov","Internet Pol Express", "Internet Pol News", "Palestine"),type = "text",omit.stat=c("f", "ser"), out = "positive.html", style = "apsr")
```

### Vdem-Interactions

```{r}
##### Electoral Democracy
m1<- lmer(dem_index~ internet_polinfo*elecdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m2<- lmer(dem_index~ internet_polexpress*elecdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m3<- lmer(dem_index~ internet_polnews*elecdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m4<- lmer(dem_index~ internet_polinfo*elecdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+(1|cname),  data = pdata4, REML =FALSE)
m5<- lmer(dem_index~ internet_polexpress*elecdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+(1|cname),  data = pdata4, REML =FALSE)

tab_model(m1, m2, m3, m4, m5,
          show.ci = FALSE,              
          show.re.var = TRUE, 
          show.se = TRUE,
          show.p = FALSE, 
          p.style = "stars",
          dv.labels = c("Model 1", "Model 2", "Model 3", 
                        "Model 4", "Model 5"),
          pred.labels = c("Intercept", "Internet Pol Info", "Elec Dem", "Unemployed", "Interest in Politics", "Age", "Education", "Female(ref:male)", "Religiosity", "Trust in Gov", "Single", "Urban", "Deference to Gov", "Internet Pol Info x Elec Dem","Internet Pol Express", "Internet Pol Express x Elec Dem","Internet Pol News", "Internet Pol News x Elec Dem" ),
          file="elec.doc")





#### Liberal Democracy

m1<- lmer(dem_index~ internet_polinfo*libdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m2<- lmer(dem_index~ internet_polexpress*libdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m3<- lmer(dem_index~ internet_polnews*libdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m4<- lmer(dem_index~ internet_polinfo*libdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+(1|cname),  data = pdata4, REML =FALSE)
m5<- lmer(dem_index~ internet_polexpress*libdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+(1|cname),  data = pdata4, REML =FALSE)

tab_model(m1, m2, m3, m4, m5,
          show.ci = FALSE,              
          show.re.var = TRUE, 
          show.se = TRUE,
          show.p = FALSE, 
          p.style = "stars",
          dv.labels = c("Model 1", "Model 2", "Model 3", 
                        "Model 4", "Model 5"),
          pred.labels = c("Intercept", "Internet Pol Info", "Lib Dem", "Unemployed", "Interest in Politics", "Age", "Education", "Female(ref:male)", "Religiosity", "Trust in Gov", "Single", "Urban", "Deference to Gov", "Internet Pol Info x Lib Dem","Internet Pol Express", "Internet Pol Express x Lib Dem","Internet Pol News", "Internet Pol News x Lib Dem" ),
          file="lib.doc")






### Participary Democracy
m1<- lmer(dem_index~ internet_polinfo*pardem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m2<- lmer(dem_index~ internet_polexpress*pardem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m3<- lmer(dem_index~ internet_polnews*pardem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m4<- lmer(dem_index~ internet_polinfo*pardem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+(1|cname),  data = pdata4, REML =FALSE)
m5<- lmer(dem_index~ internet_polexpress*pardem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+(1|cname),  data = pdata4, REML =FALSE)

tab_model(m1, m2, m3, m4, m5,
          show.ci = FALSE,              
          show.re.var = TRUE, 
          show.se = TRUE,
          show.p = FALSE, 
          p.style = "stars",
          dv.labels = c("Model 1", "Model 2", "Model 3", 
                        "Model 4", "Model 5"),
          pred.labels = c("Intercept", "Internet Pol Info", "Par Dem", "Unemployed", "Interest in Politics", "Age", "Education", "Female(ref:male)", "Religiosity", "Trust in Gov", "Single", "Urban", "Deference to Gov", "Internet Pol Info x Par Dem","Internet Pol Express", "Internet Pol Express x Par Dem","Internet Pol News", "Internet Pol News x Par Dem" ),
          file="par.doc")





### Deliberate Democracy 

m1<- lmer(dem_index~ internet_polinfo*delibdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m2<- lmer(dem_index~ internet_polexpress*delibdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m3<- lmer(dem_index~ internet_polnews*delibdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m4<- lmer(dem_index~ internet_polinfo*delibdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+(1|cname),  data = pdata4, REML =FALSE)
m5<- lmer(dem_index~ internet_polexpress*delibdem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+(1|cname),  data = pdata4, REML =FALSE)

tab_model(m1, m2, m3, m4, m5,
          show.ci = FALSE,              
          show.re.var = TRUE, 
          show.se = TRUE,
          show.p = FALSE, 
          p.style = "stars",
          dv.labels = c("Model 1", "Model 2", "Model 3", 
                        "Model 4", "Model 5"),
          pred.labels = c("Intercept", "Internet Pol Info", "Delib Dem", "Unemployed", "Interest in Politics", "Age", "Education", "Female(ref:male)", "Religiosity", "Trust in Gov", "Single", "Urban", "Deference to Gov", "Internet Pol Info x Delib Dem","Internet Pol Express", "Internet Pol Express x Delib Dem","Internet Pol News", "Internet Pol News x Delib Dem" ),
          file="delib.doc")




### Egalitarian Democracy

m1<- lmer(dem_index~ internet_polinfo*egaldem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m2<- lmer(dem_index~ internet_polexpress*egaldem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m3<- lmer(dem_index~ internet_polnews*egaldem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m4<- lmer(dem_index~ internet_polinfo*egaldem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+(1|cname),  data = pdata4, REML =FALSE)
m5<- lmer(dem_index~ internet_polexpress*egaldem_c+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+(1|cname),  data = pdata4, REML =FALSE)

tab_model(m1, m2, m3, m4, m5,
          show.ci = FALSE,              
          show.re.var = TRUE, 
          show.se = TRUE,
          show.p = FALSE, 
          p.style = "stars",
          dv.labels = c("Model 1", "Model 2", "Model 3", 
                        "Model 4", "Model 5"),
          pred.labels = c("Intercept", "Internet Pol Info", "Egal Dem", "Unemployed", "Interest in Politics", "Age", "Education", "Female(ref:male)", "Religiosity", "Trust in Gov", "Single", "Urban", "Deference to Gov", "Internet Pol Info x Egal Dem","Internet Pol Express", "Internet Pol Express x Egal Dem","Internet Pol News", "Internet Pol News x Egal Dem" ),
          file="egal.doc")









#### Regime Categorizations

m1<- lmer(dem_index~ internet_polinfo*as.factor(regime)+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m2<- lmer(dem_index~ internet_polexpress*as.factor(regime)+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m3<- lmer(dem_index~ internet_polnews*as.factor(regime)+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+deference+(1|cname),  data = pdata3, REML =FALSE)
m4<- lmer(dem_index~ internet_polinfo*as.factor(regime)+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+(1|cname),  data = pdata4, REML =FALSE)
m5<- lmer(dem_index~ internet_polexpress*as.factor(regime)+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+(1|cname),  data = pdata4, REML =FALSE)

tab_model(m1, m2, m3, m4, m5,
          show.ci = FALSE,              
          show.re.var = TRUE, 
          show.se = TRUE,
          show.p = FALSE, 
          p.style = "stars",
          dv.labels = c("Model 1", "Model 2", "Model 3", 
                        "Model 4", "Model 5"),
          pred.labels = c("Intercept", "Internet Pol Info", "Electoral Autocracy", "Unemployed", "Interest in Politics", "Age", "Education", "Female(ref:male)", "Religiosity", "Trust in Gov", "Single", "Urban", "Deference to Gov", "Internet Pol Info x Electoral Autocracy","Internet Pol Express", "Internet Pol Express x Electoral Autocracy","Internet Pol News", "Internet Pol News x Electoral Autocracy" ),
          file="regime.doc")


# v2x_polyarchy      elecdem_c
# v2x_libdem         libdem_c
# v2x_partipdem      pardem_c
# v2x_delibdem       delibdem_c
# v2x_egaldem        egaldem_c

AIC(m1, m2, m3, m4, m5, m6)
BIC(m1, m2, m3, m4, m5, m6)


vif(m1)
vif(m2)
vif(m3)
vif(m4)
vif(m5)
vif(m6)
```

### Additional Models

```{r}
## Logistic  
m1<- glm(dem_bi~ internet_polinfo,  data = pdata4, family = "binomial")
m2<- glm(dem_bi~ internet_polinfo+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname,  data = pdata4, family = "binomial")
m3<- glm(dem_bi~ internet_polexpress,  data = pdata4, family = "binomial")
m4<- glm(dem_bi~ internet_polexpress+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname,  data = pdata4,family = "binomial")
m5<- glm(dem_bi~ internet_use,  data = pdata4, family = "binomial")
m6<- glm(dem_bi~ internet_use+deference+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname,  data = pdata4, family = "binomial")
stargazer(m1, m2, m3, m4, m5, m6, type = "text",
           omit.stat = c("f", "ser"))

## multinom
m1<- multinom(dem~ internet_polinfo,  data = pdata4)
m2<- multinom(dem~ internet_polinfo+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname,  data = pdata4)
m3<- multinom(dem~ internet_polexpress,  data = pdata4)
m4<- multinom(dem~ internet_polexpress+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname,  data = pdata4)
m5<- multinom(dem~ internet_use,  data = pdata4)
m6<- multinom(dem~ internet_use+unemployed+pol_inter+age+educ+female+religious+gov_trust+single+urban+cname,  data = pdata4)
stargazer(m1, m2, m3, m4, m5, m6, type = "text",
          omit.stat = c("f", "ser"))
```
